/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_dennajort_fibonacciservice_FibonacciCalculator */
#ifndef _Included_fr_dennajort_fibonacciservice_FibonacciCalculator
#define _Included_fr_dennajort_fibonacciservice_FibonacciCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
* Class: fr_dennajort_fibonacciservice_FibonacciCalculator
* Method: nativeRecursive
* Signature: (J)J
*/
JNIEXPORT jlong JNICALL Java_fr_dennajort_fibonacciservice_FibonacciCalculator_nativeRecursive
(JNIEnv *, jclass, jlong);
/*
* Class: fr_dennajort_fibonacciservice_FibonacciCalculator
* Method: nativeIterative
* Signature: (J)J
*/
JNIEXPORT jlong JNICALL Java_fr_dennajort_fibonacciservice_FibonacciCalculator_nativeIterative
(JNIEnv *, jclass, jlong);
#ifdef __cplusplus
}
#endif
#endif